### ISSUE TITLE
gallery.json is not populated as in description

### ISSUE THREAD

**Issue by pleabargain** [haltakov/simple-photo-gallery#105]
I'm running 
simple-photo-gallery          1.5.0

https://github.com/haltakov/simple-photo-gallery/blob/master/doc/GalleryConfiguration.md

https://i.imgur.com/MUJbLDh.png

I was looking for a way to enable description in the gallery.json but the param was not there.
disbale_captions (which is a typo too, I posted that fix here: https://github.com/haltakov/simple-photo-gallery/pull/104

![image](https://user-images.githubusercontent.com/640846/113477374-08dc8700-948a-11eb-94c5-6946628fae16.png)

I'm having trouble importing the pip file into the python terminal to sort the CORRECT usage of disable_captions

**Comment by haltakov** [comment]
The default behavior is that you don't need to set `disable_captions` to `false` to have the captions. So, is the problem that you are not seeing any captions?

**Comment by pleabargain** [comment]
The problem is that there is NO option in the gallery.json to turn them on or off :) Gallery json doesn't have a caption disable option.

**Comment by haltakov** [comment]
Sorry, I kind of forgot about this thread...

I think I see your point - in the `gallery.json` that is created, there is no `disable_captions` entry, right? You can just add it yourself, but I agree it will be better to have one by default there as well.

**Comment by haltakov** [comment]
OK, I fixed it now. I also found a bug that the parameter didn't work at all and fixed it as well. You can check it with version 1.5.2.

**Comment by pleabargain** [comment]
Thank you! Will do!
