### ISSUE TITLE
Documentation issue on the PyPi page -404

### ISSUE THREAD

**Issue by jonhenke** [haltakov/simple-photo-gallery#112]
The PyPi page https://pypi.org/project/simple-photo-gallery/ includes details on Example Usage. The link for Usage results in a 404.

"
Example Usage
You can quickly create a gallery with the default settings. For more detailed information see [[Usage.]]"

https://pypi.org/project/simple-photo-gallery/doc/Usage.md >> 404

Link should be redirected to Github usage
https://github.com/haltakov/simple-photo-gallery/blob/master/doc/Usage.md

**Comment by jonhenke** [comment]
404 Issue also with the link https://pypi.org/project/simple-photo-gallery/doc/GalleryConfiguration.md on the pypi page.

**Comment by haltakov** [comment]
Thanks for catching this! It is now fixed
