### ISSUE TITLE
Error Generating images_data.json

### ISSUE THREAD

**Issue by DiverXer0** [haltakov/simple-photo-gallery#114]
Getting the following error when gallery-build

`Something went wrong while generating the images_data.json file: 'utf-8' codec can't decode byte 0xfa in position 62: invalid start byte`

Windows 10 / Python 3.9.1

Tried on the Mac as well with the same issue

**Comment by DiverXer0** [comment]
Still getting the same error unfortunately

**Comment by haltakov** [comment]
Hey, there was a bug in the captions config. It is solved with 1.5.4, so maybe you can give it a try now again. Otherwise, could you please send me the photo that causes the problem and I can investigate.

**Comment by DiverXer0** [comment]
Sorry for the late reply - I've updated and unfortunately no change and getting the same error - happy to send you the photos.

**Comment by kroesche** [comment]
I know this is a really old issue OP, but if you are still interested in this bug and getting this message, I can look at it. Can you  put the images in a read-only link somewhere (like on google drive) and post the link here. As soon as I pick up the images you can delete the share.

You might be able to put the files here in the issue, I see there is a way to add images, you can try that too.

**Comment by kroesche** [comment]
I am going to close this due to age. If you want to pursue this issue, please re-open or create a new issue.
