### ISSUE TITLE
error in images_data json. executable_path

### ISSUE THREAD

**Issue by fkgruber** [haltakov/simple-photo-gallery#131]
I'm getting an error when running gallery-build on a Google photos album. I get:
 > gallery-build
> Building the Simple Photo Gallery...
> Generating thumbnails...
> Generating the images_data.json file...
> Starting Firefox webdriver...
> Something went wrong while generating the images_data.json file: __init__() got an unexpected keyword argument 'executable_path'

Am I missing some utility or setting?
thanks
FKG

**Comment by kroesche** [comment]
Addressed in release 1.5.6
