### ISSUE TITLE
Remove exif data

### ISSUE THREAD

**Issue by tyeeman** [haltakov/simple-photo-gallery#92]
Great work here, I love it! Just wondering how to remove "Olympus Digital Camera" from showing up on my images? Edit the template somewhere??

**Comment by haltakov** [comment]
Thanks, I'm glad you like it! 

There are a couple of ways to achieve what you want.

**1. Remove the image `alt` attribute:**
You can edit the `templates/gallery_macros.jinja` file and remote the description from the `alt` attribute. This is the exact row in the example gallery: https://github.com/haltakov/simple-photo-gallery/blob/451b1c6a7f1911de238e1108fe9cdd675b4e55aa/examples/gallery_usa_simple/templates/gallery_macros.jinja#L13

**2. Remove the reading of the description from the JS code:**
Remove this line from the `public/js/main.js`
https://github.com/haltakov/simple-photo-gallery/blob/451b1c6a7f1911de238e1108fe9cdd675b4e55aa/examples/gallery_usa_simple/public/js/main.js#L9

**3. Use `exiftool` to remove the descriptions from your photos:**
Download [`exiftool`](https://exiftool.org/) and run this command. It will remove the ImageDescription metadata from your files. Be aware that this will modify your images, so better make a backup.
```
exiftool -ImageDescription="" public/images/photos/* -overwrite_original
```

**4. Option to deactivate the generation of the captions.**
If you want I can also easily add an option to not create the captions. Do you think it will be useful?

**Comment by tyeeman** [comment]
Yes, please add an option to not create the captions (leave blank), but leave the line where we can enter them at any time.
