### ISSUE TITLE
Easy top menu?

### ISSUE THREAD

**Issue by tyeeman** [haltakov/simple-photo-gallery#94]
Greetings again - Just wondering if there is a simple way to make a nice horizontal menu at the top? I'm not a coder and I don't expect you to make one but if you could point me to a website that has one I could read about then copy/paste/edit that would be appreciated. I'll search also for a bootstrap menu.

**Comment by tyeeman** [comment]
Actually I just went to the getbootstrap.com site and it seems pretty easy.

**Comment by haltakov** [comment]
As you mentioned, Bootstrap is a good way to start, because there are many examples. An alternative worth taking a look at is [TailwindCSS](https://tailwindcss.com/). It is a bit more difficult to use, but I find it much more powerful.
